INFO 2023-09-30 11:44:51,360 autoreload 19864 16740 Watching for file changes with StatReloader
INFO 2023-09-30 11:44:52,779 basehttp 19864 1824 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 11:44:52,976 basehttp 19864 11748 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 11:44:58,004 basehttp 19864 1824 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:44:58,053 basehttp 19864 11748 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:44:59,762 basehttp 19864 1824 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:44:59,797 basehttp 19864 11748 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:44:59,934 basehttp 19864 1824 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:44:59,965 basehttp 19864 11748 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,099 basehttp 19864 1824 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,132 basehttp 19864 11748 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,258 basehttp 19864 1824 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,293 basehttp 19864 11748 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,415 basehttp 19864 1824 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,449 basehttp 19864 11748 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,567 basehttp 19864 1824 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:45:00,598 basehttp 19864 11748 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:46:25,552 autoreload 19864 16740 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:46:25,989 autoreload 13812 11176 Watching for file changes with StatReloader
INFO 2023-09-30 11:46:31,355 autoreload 13812 11176 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:46:31,728 autoreload 9580 1632 Watching for file changes with StatReloader
INFO 2023-09-30 11:46:36,947 autoreload 9580 1632 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:46:37,372 autoreload 3252 18292 Watching for file changes with StatReloader
INFO 2023-09-30 11:46:44,774 autoreload 3252 18292 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:46:45,185 autoreload 9664 8252 Watching for file changes with StatReloader
INFO 2023-09-30 11:46:50,535 autoreload 9664 8252 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:46:50,928 autoreload 13820 1944 Watching for file changes with StatReloader
INFO 2023-09-30 11:47:35,341 autoreload 13820 1944 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:47:35,726 autoreload 19020 21164 Watching for file changes with StatReloader
INFO 2023-09-30 11:47:59,468 autoreload 19020 21164 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:47:59,895 autoreload 21496 8080 Watching for file changes with StatReloader
INFO 2023-09-30 11:48:25,729 autoreload 21496 8080 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:48:26,127 autoreload 3312 21308 Watching for file changes with StatReloader
INFO 2023-09-30 11:49:04,140 autoreload 3312 21308 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:49:04,578 autoreload 17648 18596 Watching for file changes with StatReloader
INFO 2023-09-30 11:49:58,259 autoreload 17648 18596 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:49:58,625 autoreload 1124 19504 Watching for file changes with StatReloader
INFO 2023-09-30 11:50:07,110 autoreload 1124 19504 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py changed, reloading.
INFO 2023-09-30 11:50:07,492 autoreload 15764 18548 Watching for file changes with StatReloader
INFO 2023-09-30 11:51:28,699 autoreload 15764 18548 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myproject\settings.py changed, reloading.
INFO 2023-09-30 11:51:29,125 autoreload 20176 12432 Watching for file changes with StatReloader
INFO 2023-09-30 11:51:51,512 autoreload 19172 11056 Watching for file changes with StatReloader
INFO 2023-09-30 11:51:52,845 basehttp 19172 2616 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 11:51:53,134 basehttp 19172 19660 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 11:52:01,535 views 19172 2616 Выпало значение: 2
INFO 2023-09-30 11:52:01,536 basehttp 19172 2616 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:52:01,569 views 19172 19660 Выпало значение: 1
INFO 2023-09-30 11:52:01,569 basehttp 19172 19660 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:52:03,179 views 19172 15428 Выпало значение: 1
INFO 2023-09-30 11:52:03,180 basehttp 19172 15428 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:52:03,215 views 19172 7232 Выпало значение: 2
INFO 2023-09-30 11:52:03,216 basehttp 19172 7232 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:52:03,628 views 19172 15428 Выпало значение: 1
INFO 2023-09-30 11:52:03,629 basehttp 19172 15428 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:52:03,664 views 19172 7232 Выпало значение: 1
INFO 2023-09-30 11:52:03,665 basehttp 19172 7232 "GET /cube/ HTTP/1.1" 200 1
INFO 2023-09-30 11:52:15,922 views 19172 15428 Выпало число: 25
INFO 2023-09-30 11:52:15,923 basehttp 19172 15428 "GET /random_number/ HTTP/1.1" 200 2
INFO 2023-09-30 11:52:15,960 views 19172 7232 Выпало число: 70
INFO 2023-09-30 11:52:15,961 basehttp 19172 7232 "GET /random_number/ HTTP/1.1" 200 2
INFO 2023-09-30 11:52:17,691 views 19172 15428 Выпало число: 73
INFO 2023-09-30 11:52:17,691 basehttp 19172 15428 "GET /random_number/ HTTP/1.1" 200 2
INFO 2023-09-30 11:52:17,727 views 19172 7232 Выпало число: 64
INFO 2023-09-30 11:52:17,728 basehttp 19172 7232 "GET /random_number/ HTTP/1.1" 200 2
INFO 2023-09-30 11:52:18,213 views 19172 15428 Выпало число: 58
INFO 2023-09-30 11:52:18,214 basehttp 19172 15428 "GET /random_number/ HTTP/1.1" 200 2
INFO 2023-09-30 11:52:18,248 views 19172 7232 Выпало число: 90
INFO 2023-09-30 11:52:18,249 basehttp 19172 7232 "GET /random_number/ HTTP/1.1" 200 2
INFO 2023-09-30 11:52:23,087 views 19172 15428 Выпала сторона: решка
INFO 2023-09-30 11:52:23,088 basehttp 19172 15428 "GET /eagle/ HTTP/1.1" 200 10
INFO 2023-09-30 11:52:23,128 views 19172 7232 Выпала сторона: орёл
INFO 2023-09-30 11:52:23,130 basehttp 19172 7232 "GET /eagle/ HTTP/1.1" 200 8
INFO 2023-09-30 11:52:24,606 views 19172 15428 Выпала сторона: решка
INFO 2023-09-30 11:52:24,607 basehttp 19172 15428 "GET /eagle/ HTTP/1.1" 200 10
INFO 2023-09-30 11:52:24,644 views 19172 7232 Выпала сторона: орёл
INFO 2023-09-30 11:52:24,645 basehttp 19172 7232 "GET /eagle/ HTTP/1.1" 200 8
INFO 2023-09-30 11:52:24,967 views 19172 15428 Выпала сторона: решка
INFO 2023-09-30 11:52:24,968 basehttp 19172 15428 "GET /eagle/ HTTP/1.1" 200 10
INFO 2023-09-30 11:52:25,005 views 19172 7232 Выпала сторона: решка
INFO 2023-09-30 11:52:25,005 basehttp 19172 7232 "GET /eagle/ HTTP/1.1" 200 10
INFO 2023-09-30 11:52:25,611 views 19172 15428 Выпала сторона: решка
INFO 2023-09-30 11:52:25,613 basehttp 19172 15428 "GET /eagle/ HTTP/1.1" 200 10
INFO 2023-09-30 11:52:25,653 views 19172 7232 Выпала сторона: орёл
INFO 2023-09-30 11:52:25,654 basehttp 19172 7232 "GET /eagle/ HTTP/1.1" 200 8
INFO 2023-09-30 11:52:25,997 views 19172 15428 Выпала сторона: орёл
INFO 2023-09-30 11:52:25,997 basehttp 19172 15428 "GET /eagle/ HTTP/1.1" 200 8
INFO 2023-09-30 11:52:26,033 views 19172 7232 Выпала сторона: решка
INFO 2023-09-30 11:52:26,033 basehttp 19172 7232 "GET /eagle/ HTTP/1.1" 200 10
INFO 2023-09-30 11:52:26,454 views 19172 15428 Выпала сторона: орёл
INFO 2023-09-30 11:52:26,454 basehttp 19172 15428 "GET /eagle/ HTTP/1.1" 200 8
INFO 2023-09-30 11:52:26,490 views 19172 7232 Выпала сторона: орёл
INFO 2023-09-30 11:52:26,490 basehttp 19172 7232 "GET /eagle/ HTTP/1.1" 200 8
INFO 2023-09-30 12:02:51,341 autoreload 13236 17940 Watching for file changes with StatReloader
INFO 2023-09-30 12:38:16,027 autoreload 15212 5344 Watching for file changes with StatReloader
INFO 2023-09-30 12:38:18,028 basehttp 15212 14904 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 12:38:18,252 basehttp 15212 8924 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 12:38:24,468 views 15212 14904 посещение страницы about в: 2023-09-30 12:38:24.468243
INFO 2023-09-30 12:38:24,469 basehttp 15212 14904 "GET /about/ HTTP/1.1" 200 1702
INFO 2023-09-30 12:38:24,535 views 15212 8924 посещение страницы about в: 2023-09-30 12:38:24.535290
INFO 2023-09-30 12:38:24,535 basehttp 15212 8924 "GET /about/ HTTP/1.1" 200 1702
INFO 2023-09-30 12:39:23,797 autoreload 15212 5344 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\homework_1\urls.py changed, reloading.
INFO 2023-09-30 12:39:24,244 autoreload 18924 1440 Watching for file changes with StatReloader
WARNING 2023-09-30 12:39:31,437 log 18924 9168 Not Found: /main_page/
WARNING 2023-09-30 12:39:31,438 basehttp 18924 9168 "GET /main_page/ HTTP/1.1" 404 3132
WARNING 2023-09-30 12:39:31,496 log 18924 21500 Not Found: /main_page/
WARNING 2023-09-30 12:39:31,497 basehttp 18924 21500 "GET /main_page/ HTTP/1.1" 404 3132
INFO 2023-09-30 12:41:07,877 autoreload 18924 1440 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myproject\settings.py changed, reloading.
INFO 2023-09-30 12:41:08,289 autoreload 18020 14248 Watching for file changes with StatReloader
WARNING 2023-09-30 12:41:09,861 log 18020 2940 Not Found: /main_page/
WARNING 2023-09-30 12:41:09,862 basehttp 18020 2940 "GET /main_page/ HTTP/1.1" 404 3132
WARNING 2023-09-30 12:41:09,914 log 18020 11432 Not Found: /main_page/
WARNING 2023-09-30 12:41:09,915 basehttp 18020 11432 "GET /main_page/ HTTP/1.1" 404 3132
INFO 2023-09-30 12:42:10,775 autoreload 19204 17416 Watching for file changes with StatReloader
INFO 2023-09-30 12:42:11,931 basehttp 19204 8800 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 12:42:12,071 basehttp 19204 8320 "GET / HTTP/1.1" 200 12
WARNING 2023-09-30 12:42:24,979 log 19204 8800 Not Found: /main_page/
WARNING 2023-09-30 12:42:24,979 basehttp 19204 8800 "GET /main_page/ HTTP/1.1" 404 3123
WARNING 2023-09-30 12:42:25,035 log 19204 8320 Not Found: /main_page/
WARNING 2023-09-30 12:42:25,036 basehttp 19204 8320 "GET /main_page/ HTTP/1.1" 404 3123
INFO 2023-09-30 12:42:39,706 autoreload 19204 17416 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\homework_1\urls.py changed, reloading.
INFO 2023-09-30 12:42:40,108 autoreload 8224 9236 Watching for file changes with StatReloader
WARNING 2023-09-30 12:42:40,511 log 8224 3292 Not Found: /main_page/
WARNING 2023-09-30 12:42:40,511 basehttp 8224 3292 "GET /main_page/ HTTP/1.1" 404 3132
WARNING 2023-09-30 12:42:40,565 log 8224 7964 Not Found: /main_page/
WARNING 2023-09-30 12:42:40,565 basehttp 8224 7964 "GET /main_page/ HTTP/1.1" 404 3132
INFO 2023-09-30 12:42:50,694 autoreload 8224 9236 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\homework_1\urls.py changed, reloading.
INFO 2023-09-30 12:42:51,104 autoreload 13756 16220 Watching for file changes with StatReloader
INFO 2023-09-30 12:42:51,506 views 13756 21140 посещение страницы index в: 2023-09-30 12:42:51.506702
INFO 2023-09-30 12:42:51,507 basehttp 13756 21140 "GET /main_page/ HTTP/1.1" 200 1779
INFO 2023-09-30 12:42:51,554 views 13756 9312 посещение страницы index в: 2023-09-30 12:42:51.554202
INFO 2023-09-30 12:42:51,555 basehttp 13756 9312 "GET /main_page/ HTTP/1.1" 200 1779
INFO 2023-09-30 13:07:02,812 autoreload 12916 1924 Watching for file changes with StatReloader
INFO 2023-09-30 13:07:05,938 basehttp 12916 19736 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 13:07:06,158 basehttp 12916 21020 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 13:07:42,099 views 12916 19736 Выпала сторона: Сторона: орёл, Время: 2023-09-30 10:07:40.702079+00:00
INFO 2023-09-30 13:07:42,101 basehttp 12916 19736 "GET /eagle/ HTTP/1.1" 200 70
INFO 2023-09-30 13:07:43,017 views 12916 21020 Выпала сторона: Сторона: орёл, Время: 2023-09-30 10:07:42.151541+00:00
INFO 2023-09-30 13:07:43,019 basehttp 12916 21020 "GET /eagle/ HTTP/1.1" 200 70
INFO 2023-09-30 13:07:45,783 views 12916 19736 Выпала сторона: Сторона: решка, Время: 2023-09-30 10:07:45.087854+00:00
INFO 2023-09-30 13:07:45,785 basehttp 12916 19736 "GET /eagle/ HTTP/1.1" 200 72
INFO 2023-09-30 13:07:46,980 views 12916 21020 Выпала сторона: Сторона: решка, Время: 2023-09-30 10:07:45.831693+00:00
INFO 2023-09-30 13:07:46,982 basehttp 12916 21020 "GET /eagle/ HTTP/1.1" 200 72
INFO 2023-09-30 13:07:49,760 views 12916 19736 Выпала сторона: Сторона: решка, Время: 2023-09-30 10:07:48.643524+00:00
INFO 2023-09-30 13:07:49,762 basehttp 12916 19736 "GET /eagle/ HTTP/1.1" 200 72
INFO 2023-09-30 13:07:50,055 views 12916 21020 Выпала сторона: Сторона: решка, Время: 2023-09-30 10:07:49.807625+00:00
INFO 2023-09-30 13:07:50,055 basehttp 12916 21020 "GET /eagle/ HTTP/1.1" 200 72
INFO 2023-09-30 13:15:54,307 autoreload 12916 1924 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:15:54,760 autoreload 14220 14832 Watching for file changes with StatReloader
INFO 2023-09-30 13:16:27,963 autoreload 14220 14832 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:16:28,403 autoreload 8284 20828 Watching for file changes with StatReloader
INFO 2023-09-30 13:18:01,797 autoreload 8284 20828 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:18:02,188 autoreload 2628 4292 Watching for file changes with StatReloader
INFO 2023-09-30 13:18:08,525 autoreload 2628 4292 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:18:08,878 autoreload 20804 8060 Watching for file changes with StatReloader
INFO 2023-09-30 13:19:05,151 autoreload 20804 8060 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:19:05,546 autoreload 15900 20604 Watching for file changes with StatReloader
INFO 2023-09-30 13:22:48,892 autoreload 15900 20604 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:22:49,268 autoreload 11532 8240 Watching for file changes with StatReloader
INFO 2023-09-30 13:23:03,807 autoreload 11532 8240 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:23:04,223 autoreload 20556 16192 Watching for file changes with StatReloader
INFO 2023-09-30 13:23:07,533 autoreload 20556 16192 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:23:07,966 autoreload 3144 1064 Watching for file changes with StatReloader
INFO 2023-09-30 13:23:10,260 autoreload 3144 1064 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:23:10,682 autoreload 9560 9540 Watching for file changes with StatReloader
INFO 2023-09-30 13:23:14,981 autoreload 9560 9540 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:23:15,382 autoreload 21452 11896 Watching for file changes with StatReloader
INFO 2023-09-30 13:23:19,723 autoreload 21452 11896 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:23:20,086 autoreload 17912 15828 Watching for file changes with StatReloader
INFO 2023-09-30 13:28:57,165 autoreload 11628 21300 Watching for file changes with StatReloader
INFO 2023-09-30 13:30:23,173 autoreload 19376 17940 Watching for file changes with StatReloader
INFO 2023-09-30 13:33:25,925 autoreload 19376 17940 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:33:26,311 autoreload 16512 1068 Watching for file changes with StatReloader
INFO 2023-09-30 13:33:57,040 autoreload 16512 1068 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:33:57,445 autoreload 6788 13108 Watching for file changes with StatReloader
INFO 2023-09-30 13:36:29,976 autoreload 5084 18436 Watching for file changes with StatReloader
INFO 2023-09-30 13:36:32,179 basehttp 5084 15648 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 13:36:32,395 basehttp 5084 14984 "GET / HTTP/1.1" 200 12
ERROR 2023-09-30 13:37:04,037 log 5084 15648 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:37:04,039 basehttp 5084 15648 "GET /show_elements/3 HTTP/1.1" 500 71174
ERROR 2023-09-30 13:37:04,219 log 5084 14984 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:37:04,221 basehttp 5084 14984 "GET /show_elements/3 HTTP/1.1" 500 70230
ERROR 2023-09-30 13:37:30,803 log 5084 15648 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:37:30,805 basehttp 5084 15648 "GET /show_elements/3 HTTP/1.1" 500 71311
ERROR 2023-09-30 13:37:30,901 log 5084 14984 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:37:30,903 basehttp 5084 14984 "GET /show_elements/3 HTTP/1.1" 500 70230
WARNING 2023-09-30 13:37:50,104 log 5084 15648 Not Found: /show_elements/
WARNING 2023-09-30 13:37:50,105 basehttp 5084 15648 "GET /show_elements/ HTTP/1.1" 404 3341
WARNING 2023-09-30 13:37:50,160 log 5084 14984 Not Found: /show_elements/
WARNING 2023-09-30 13:37:50,161 basehttp 5084 14984 "GET /show_elements/ HTTP/1.1" 404 3341
INFO 2023-09-30 13:38:30,017 autoreload 5084 18436 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:38:30,414 autoreload 17664 12648 Watching for file changes with StatReloader
ERROR 2023-09-30 13:38:32,807 log 17664 13436 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 26, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'all'
ERROR 2023-09-30 13:38:32,809 basehttp 17664 13436 "GET /show_elements/3 HTTP/1.1" 500 71166
ERROR 2023-09-30 13:38:32,907 log 17664 15140 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 26, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'all'
ERROR 2023-09-30 13:38:32,909 basehttp 17664 15140 "GET /show_elements/3 HTTP/1.1" 500 70222
INFO 2023-09-30 13:40:11,045 autoreload 17664 12648 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:40:11,410 autoreload 10316 2944 Watching for file changes with StatReloader
INFO 2023-09-30 13:40:14,853 basehttp 10316 21108 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 13:40:15,247 basehttp 10316 13120 "GET / HTTP/1.1" 200 12
ERROR 2023-09-30 13:40:26,085 log 10316 21108 Internal Server Error: /eagle/
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 14, in eagle
    coin.save()
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2023-09-30 13:40:26,089 basehttp 10316 21108 "GET /eagle/ HTTP/1.1" 500 128061
ERROR 2023-09-30 13:40:31,662 log 10316 2188 Internal Server Error: /eagle/
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 14, in eagle
    coin.save()
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2023-09-30 13:40:31,665 basehttp 10316 2188 "GET /eagle/ HTTP/1.1" 500 128061
ERROR 2023-09-30 13:40:37,245 log 10316 13120 Internal Server Error: /eagle/
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 14, in eagle
    coin.save()
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2023-09-30 13:40:37,248 basehttp 10316 13120 "GET /eagle/ HTTP/1.1" 500 127099
INFO 2023-09-30 13:40:52,364 views 10316 2188 Выпала сторона: Сторона: орёл, Время: 2023-09-30 10:40:51.376033+00:00
INFO 2023-09-30 13:40:52,365 basehttp 10316 2188 "GET /eagle/ HTTP/1.1" 200 70
INFO 2023-09-30 13:40:53,180 views 10316 13120 Выпала сторона: Сторона: орёл, Время: 2023-09-30 10:40:52.407142+00:00
INFO 2023-09-30 13:40:53,182 basehttp 10316 13120 "GET /eagle/ HTTP/1.1" 200 70
INFO 2023-09-30 13:40:54,730 views 10316 2188 Выпала сторона: Сторона: решка, Время: 2023-09-30 10:40:54.542462+00:00
INFO 2023-09-30 13:40:54,732 basehttp 10316 2188 "GET /eagle/ HTTP/1.1" 200 72
INFO 2023-09-30 13:40:54,951 views 10316 13120 Выпала сторона: Сторона: орёл, Время: 2023-09-30 10:40:54.778600+00:00
INFO 2023-09-30 13:40:54,953 basehttp 10316 13120 "GET /eagle/ HTTP/1.1" 200 70
INFO 2023-09-30 13:40:56,678 views 10316 2188 Выпала сторона: Сторона: орёл, Время: 2023-09-30 10:40:56.519539+00:00
INFO 2023-09-30 13:40:56,679 basehttp 10316 2188 "GET /eagle/ HTTP/1.1" 200 70
INFO 2023-09-30 13:40:56,862 views 10316 13120 Выпала сторона: Сторона: решка, Время: 2023-09-30 10:40:56.745792+00:00
INFO 2023-09-30 13:40:56,863 basehttp 10316 13120 "GET /eagle/ HTTP/1.1" 200 72
WARNING 2023-09-30 13:41:02,739 log 10316 2188 Not Found: /show_elements/
WARNING 2023-09-30 13:41:02,740 basehttp 10316 2188 "GET /show_elements/ HTTP/1.1" 404 3341
WARNING 2023-09-30 13:41:02,789 log 10316 13120 Not Found: /show_elements/
WARNING 2023-09-30 13:41:02,789 basehttp 10316 13120 "GET /show_elements/ HTTP/1.1" 404 3341
ERROR 2023-09-30 13:41:08,664 log 10316 2188 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:41:08,666 basehttp 10316 2188 "GET /show_elements/3 HTTP/1.1" 500 71174
ERROR 2023-09-30 13:41:08,759 log 10316 13120 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:41:08,761 basehttp 10316 13120 "GET /show_elements/3 HTTP/1.1" 500 70230
INFO 2023-09-30 13:45:18,111 autoreload 10316 2944 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:45:18,508 autoreload 20952 18308 Watching for file changes with StatReloader
INFO 2023-09-30 13:45:24,950 autoreload 20952 18308 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:45:25,372 autoreload 20852 15492 Watching for file changes with StatReloader
INFO 2023-09-30 13:45:33,833 autoreload 20852 15492 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:45:34,215 autoreload 19928 9876 Watching for file changes with StatReloader
INFO 2023-09-30 13:46:12,292 autoreload 19928 9876 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:46:12,672 autoreload 6972 6584 Watching for file changes with StatReloader
INFO 2023-09-30 13:47:00,231 autoreload 16468 13468 Watching for file changes with StatReloader
INFO 2023-09-30 13:47:09,325 basehttp 16468 3488 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 13:47:09,528 basehttp 16468 16644 "GET / HTTP/1.1" 200 12
ERROR 2023-09-30 13:47:26,993 log 16468 3488 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:47:26,995 basehttp 16468 3488 "GET /show_elements/3 HTTP/1.1" 500 71635
ERROR 2023-09-30 13:47:27,248 log 16468 3488 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:47:27,250 basehttp 16468 3488 "GET /show_elements/3 HTTP/1.1" 500 71361
ERROR 2023-09-30 13:47:27,388 log 16468 16644 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:47:27,390 basehttp 16468 16644 "GET /show_elements/3 HTTP/1.1" 500 70417
INFO 2023-09-30 13:53:39,760 autoreload 17816 14340 Watching for file changes with StatReloader
INFO 2023-09-30 13:53:40,890 basehttp 17816 8844 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 13:53:41,095 basehttp 17816 13476 "GET / HTTP/1.1" 200 12
ERROR 2023-09-30 13:53:46,230 log 17816 8844 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:53:46,232 basehttp 17816 8844 "GET /show_elements/3 HTTP/1.1" 500 71635
ERROR 2023-09-30 13:53:46,520 log 17816 8844 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:53:46,521 basehttp 17816 8844 "GET /show_elements/3 HTTP/1.1" 500 71361
ERROR 2023-09-30 13:53:46,658 log 17816 13476 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:53:46,660 basehttp 17816 13476 "GET /show_elements/3 HTTP/1.1" 500 70417
ERROR 2023-09-30 13:54:18,647 log 17816 8844 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:54:18,649 basehttp 17816 8844 "GET /show_elements/3 HTTP/1.1" 500 71498
ERROR 2023-09-30 13:54:18,871 log 17816 13476 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 25, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 13:54:18,873 basehttp 17816 13476 "GET /show_elements/3 HTTP/1.1" 500 70417
INFO 2023-09-30 13:55:51,185 autoreload 17816 14340 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:55:51,556 autoreload 19596 19124 Watching for file changes with StatReloader
INFO 2023-09-30 13:59:14,124 autoreload 19596 19124 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 13:59:14,565 autoreload 10868 8224 Watching for file changes with StatReloader
INFO 2023-09-30 14:01:44,912 autoreload 10868 8224 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\urls.py changed, reloading.
INFO 2023-09-30 14:01:45,300 autoreload 2784 8964 Watching for file changes with StatReloader
INFO 2023-09-30 14:01:45,483 basehttp 2784 20000 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 14:01:45,692 basehttp 2784 13892 "GET / HTTP/1.1" 200 12
WARNING 2023-09-30 14:01:54,596 log 2784 20000 Not Found: /show_elements
WARNING 2023-09-30 14:01:54,596 basehttp 2784 20000 "GET /show_elements HTTP/1.1" 404 3338
WARNING 2023-09-30 14:01:54,655 log 2784 13892 Not Found: /show_elements
WARNING 2023-09-30 14:01:54,656 basehttp 2784 13892 "GET /show_elements HTTP/1.1" 404 3338
ERROR 2023-09-30 14:01:58,110 log 2784 20000 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 22, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 14:01:58,112 basehttp 2784 20000 "GET /show_elements/3 HTTP/1.1" 500 71650
ERROR 2023-09-30 14:01:58,442 log 2784 20000 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 22, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 14:01:58,444 basehttp 2784 20000 "GET /show_elements/3 HTTP/1.1" 500 71376
ERROR 2023-09-30 14:01:58,567 log 2784 13892 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 22, in counter
    coins = Coin.object.all()
            ^^^^^^^^^^^
AttributeError: type object 'Coin' has no attribute 'object'
ERROR 2023-09-30 14:01:58,569 basehttp 2784 13892 "GET /show_elements/3 HTTP/1.1" 500 70432
INFO 2023-09-30 14:08:26,104 autoreload 2784 8964 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:08:26,463 autoreload 15996 12108 Watching for file changes with StatReloader
INFO 2023-09-30 14:08:27,955 basehttp 15996 8140 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 14:08:28,161 basehttp 15996 9444 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 14:08:35,276 basehttp 15996 8140 "GET /show_elements/3 HTTP/1.1" 200 236
INFO 2023-09-30 14:08:35,418 basehttp 15996 9444 "GET /show_elements/3 HTTP/1.1" 200 236
INFO 2023-09-30 14:52:55,044 autoreload 13548 20520 Watching for file changes with StatReloader
INFO 2023-09-30 14:53:04,437 autoreload 13548 20520 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:53:04,873 autoreload 15004 10420 Watching for file changes with StatReloader
INFO 2023-09-30 14:53:06,772 basehttp 15004 16324 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 14:53:07,012 basehttp 15004 17832 "GET / HTTP/1.1" 200 12
ERROR 2023-09-30 14:53:12,279 log 15004 16324 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 22, in counter
    coins = Coin.objects.all()[-1:-n - 1:-1]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\query.py", line 429, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2023-09-30 14:53:12,283 basehttp 15004 16324 "GET /show_elements/3 HTTP/1.1" 500 76918
ERROR 2023-09-30 14:53:12,436 log 15004 17832 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 22, in counter
    coins = Coin.objects.all()[-1:-n - 1:-1]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\db\models\query.py", line 429, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2023-09-30 14:53:12,438 basehttp 15004 17832 "GET /show_elements/3 HTTP/1.1" 500 75974
INFO 2023-09-30 14:57:17,447 autoreload 15004 10420 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:57:17,855 autoreload 13848 16980 Watching for file changes with StatReloader
INFO 2023-09-30 14:57:29,336 autoreload 13848 16980 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:57:29,701 autoreload 15668 17092 Watching for file changes with StatReloader
INFO 2023-09-30 14:57:40,636 basehttp 15668 20424 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 14:57:40,775 basehttp 15668 17652 "GET / HTTP/1.1" 200 12
INFO 2023-09-30 14:57:41,347 autoreload 15668 17092 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:57:41,724 autoreload 14104 20520 Watching for file changes with StatReloader
ERROR 2023-09-30 14:57:47,407 log 14104 6104 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 29, in counter
    coins_dict['решка'] +=1
    ~~~~~~~~~~^^^^^^^^^
KeyError: 'решка'
ERROR 2023-09-30 14:57:47,411 basehttp 14104 6104 "GET /show_elements/3 HTTP/1.1" 500 71911
ERROR 2023-09-30 14:57:47,553 log 14104 8724 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 29, in counter
    coins_dict['решка'] +=1
    ~~~~~~~~~~^^^^^^^^^
KeyError: 'решка'
ERROR 2023-09-30 14:57:47,555 basehttp 14104 8724 "GET /show_elements/3 HTTP/1.1" 500 70967
INFO 2023-09-30 14:58:15,778 autoreload 14104 20520 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:58:16,158 autoreload 15492 15720 Watching for file changes with StatReloader
INFO 2023-09-30 14:58:49,130 autoreload 15492 15720 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:58:49,507 autoreload 14392 18372 Watching for file changes with StatReloader
ERROR 2023-09-30 14:58:52,494 log 14392 9896 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 29, in counter
    coins_dict['решка'] += 1
    ~~~~~~~~~~^^^^^^^^^
KeyError: 'решка'
ERROR 2023-09-30 14:58:52,495 basehttp 14392 9896 "GET /show_elements/3 HTTP/1.1" 500 72051
ERROR 2023-09-30 14:58:52,592 log 14392 7032 Internal Server Error: /show_elements/3
Traceback (most recent call last):
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\games_app\views.py", line 20, in show_elements
    return HttpResponse(f'{Coin.counter(n)}')
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py", line 29, in counter
    coins_dict['решка'] += 1
    ~~~~~~~~~~^^^^^^^^^
KeyError: 'решка'
ERROR 2023-09-30 14:58:52,594 basehttp 14392 7032 "GET /show_elements/3 HTTP/1.1" 500 70970
INFO 2023-09-30 14:59:42,050 autoreload 14392 18372 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 14:59:42,443 autoreload 21488 2948 Watching for file changes with StatReloader
INFO 2023-09-30 14:59:57,083 basehttp 21488 4652 "GET /show_elements/3 HTTP/1.1" 200 32
INFO 2023-09-30 14:59:57,138 basehttp 21488 17012 "GET /show_elements/3 HTTP/1.1" 200 32
INFO 2023-09-30 14:59:59,063 basehttp 21488 4652 "GET /show_elements/3 HTTP/1.1" 200 32
INFO 2023-09-30 14:59:59,110 basehttp 21488 17012 "GET /show_elements/3 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:04,725 basehttp 21488 4652 "GET /show_elements/5 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:04,768 basehttp 21488 17012 "GET /show_elements/5 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:08,398 basehttp 21488 4652 "GET /show_elements/4 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:08,445 basehttp 21488 17012 "GET /show_elements/4 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:28,118 basehttp 21488 4652 "GET /show_elements/7 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:28,164 basehttp 21488 17012 "GET /show_elements/7 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:32,964 basehttp 21488 4652 "GET /show_elements/8 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:33,010 basehttp 21488 17012 "GET /show_elements/8 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:36,556 basehttp 21488 4652 "GET /show_elements/10 HTTP/1.1" 200 32
INFO 2023-09-30 15:00:36,599 basehttp 21488 17012 "GET /show_elements/10 HTTP/1.1" 200 32
INFO 2023-09-30 15:02:10,237 autoreload 21488 2948 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 15:02:10,631 autoreload 7248 9244 Watching for file changes with StatReloader
INFO 2023-09-30 15:02:35,340 autoreload 7248 9244 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 15:02:35,740 autoreload 4992 14876 Watching for file changes with StatReloader
INFO 2023-09-30 15:02:42,058 autoreload 4992 14876 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 15:02:42,468 autoreload 5316 4956 Watching for file changes with StatReloader
INFO 2023-09-30 15:02:46,752 autoreload 5316 4956 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 15:02:47,138 autoreload 11092 20520 Watching for file changes with StatReloader
INFO 2023-09-30 15:02:52,503 autoreload 11092 20520 C:\Users\dima4\Documents\GeekBrains\Programmer\000_Tech_spec\Django\project-django\myapp2\models.py changed, reloading.
INFO 2023-09-30 15:02:52,888 autoreload 16448 2664 Watching for file changes with StatReloader
